travis:
  secure:
    BINSTAR_TOKEN: kbuAZr5UR6zqUwx0pBUOxM9oCbk2E5hU14TiI7ZYC2y6jgl7iZGhXSD48Jt6KMxcQ3Jqx1MODYFvypaNijLqe0/4RM4HH2cdJpviaDTzPT+TOGptuaRLyDBQ33+NCQuZTTygNovILdceh4AGSuIMqNml3SizPTy2DjV+ebOplgjpbBwqnfwQmhHycO518qemFW/9+0FP97xm7bqP6Xzb+hqG8KSUlpp30mZ02AoutO2QCRG65McnYY04YoRkJ7xfh0ZTII5TKsD2PBzcm+9qsXW8LgULH3wmkcoargcDg7np8NL97P4qrVKjVR8XigGAWlGuU5e16kJ2IPhhiEIKS5rWn/g10hrchtQ1SYjt/jW+q9d4h/pXoLhTx0cHdRFvAFjvm7EbdM84zEmTXN3jYEuCZ+fH8wJc04y4THHqOxf/r7kHhm4x/FMzwVL28zhAb0n+fII0ZvKsNdgxvIvC8Xs4Wpj4hKhxUjM2lyd0xf6BzDI94akgjWkTlMIOOZRjUvSIA/XnE8SD05Uzu43b/zQfPOZtEqXNdQ+fgtS7wjuqZ1J3dQtc9+9S+LyWs+PHkGhL+dS84HVco765u6z6+oj/4ZKEEO3FsPrN8YL/WFJBV2VNhjquhPTaXhnUmJh3XWFcOcd/yZuxk2PB9qeAVIvo0tUFCABXrHacy6/YB6Y=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
